/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import controlar.Controla_atleta;
import projeto_delegacao.Cadastro_atletas;
/**
 *
 * @author lucas
 */
public class Interface_principal extends javax.swing.JFrame {
    
    Controla_atleta ca;
    /**
     * Creates new form Principal
     */
    public Interface_principal() {
        initComponents();
        ca = new Controla_atleta();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdp_principal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jmenu_principal = new javax.swing.JMenuBar();
        jmenu_cadastrar = new javax.swing.JMenu();
        jmenu_subCadastrar = new javax.swing.JMenuItem();
        jmenu_listar = new javax.swing.JMenu();
        jmenu_subListar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Desenvolvido por Lucas");

        jdp_principal.setBackground(new java.awt.Color(204, 255, 255));
        jdp_principal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jdp_principal.setForeground(new java.awt.Color(153, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/capa.png"))); // NOI18N

        jdp_principal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdp_principalLayout = new javax.swing.GroupLayout(jdp_principal);
        jdp_principal.setLayout(jdp_principalLayout);
        jdp_principalLayout.setHorizontalGroup(
            jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdp_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );
        jdp_principalLayout.setVerticalGroup(
            jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp_principalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );

        jmenu_cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jmenu_cadastrar.setText("Cadastro");
        jmenu_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_cadastrarActionPerformed(evt);
            }
        });

        jmenu_subCadastrar.setText("Cadastrar atleta");
        jmenu_subCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_subCadastrarActionPerformed(evt);
            }
        });
        jmenu_cadastrar.add(jmenu_subCadastrar);

        jmenu_principal.add(jmenu_cadastrar);

        jmenu_listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        jmenu_listar.setText("Listar atletas");

        jmenu_subListar.setText("Listar atletas cadastrados");
        jmenu_subListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_subListarActionPerformed(evt);
            }
        });
        jmenu_listar.add(jmenu_subListar);

        jmenu_principal.add(jmenu_listar);

        setJMenuBar(jmenu_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp_principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdp_principal)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(426, 378));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmenu_subCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_subCadastrarActionPerformed
    
    Cadastro_atletas obj = new Cadastro_atletas();
    jdp_principal.add(obj);
    obj.setVisible(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_jmenu_subCadastrarActionPerformed

    private void jmenu_subListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_subListarActionPerformed
        
        Mostra_atletas obj = new Mostra_atletas(null, true, ca);
        //jdp_principal.add(obj);
        obj.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenu_subListarActionPerformed

    private void jmenu_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_cadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenu_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JDesktopPane jdp_principal;
    private javax.swing.JMenu jmenu_cadastrar;
    private javax.swing.JMenu jmenu_listar;
    private javax.swing.JMenuBar jmenu_principal;
    private javax.swing.JMenuItem jmenu_subCadastrar;
    private javax.swing.JMenuItem jmenu_subListar;
    // End of variables declaration//GEN-END:variables
}
